"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.
Customised for the "Mini Shop" demo that exercises every library from the spec.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-r=b@q9@-6x8=y^dni$gimb-3#^a=p__=6y*=-x!$z9kis^)^4a"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",                # required by django-allauth
    # ── Third-party ──────────────────────────────────────────────────────
    "rest_framework",                      # Django REST Framework
    "rest_framework.authtoken",            # DRF token model (used by auth_kit)
    "django_extensions",                   # django-extensions  (shell_plus, graph_models …)
    "django_filters",                      # django-filter      (FilterSet on views)
    "taggit",                              # django-taggit      (TaggableManager)
    "eav",                                 # django-eav2        (Entity-Attribute-Value)
    "payments",                            # django-payments    (BasePayment + dummy provider)
    "django_bolt",                         # Django-Bolt        (high-perf ASGI endpoints)
    "drf_spectacular",                     # OpenAPI schema     (also required by auth_kit)
    # ── Authentication ───────────────────────────────────────────────────
    "allauth",                             # django-allauth     (registration / social login)
    "allauth.account",
    "allauth.socialaccount",
    # ── Project ──────────────────────────────────────────────────────────
    "core",                                # our single "Mini Shop" app
]

SITE_ID = 1  # required by django-allauth

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",        # django-allauth
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []  # intentionally empty for easy demo passwords


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ==========================================================================
#  THIRD-PARTY LIBRARY SETTINGS
# ==========================================================================

# ── Django REST Framework ─────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "auth_kit.authentication.JWTCookieAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# ── django-allauth ───────────────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_EMAIL_VERIFICATION = "none"       # skip e-mail verification for demo
ACCOUNT_SIGNUP_FIELDS = ["email", "username*", "password1*", "password2*"]

# ── drf-auth-kit  (wraps allauth + simplejwt for REST API auth) ──────────
AUTH_KIT = {
    "AUTH_TYPE": "jwt",
    "USE_AUTH_COOKIE": True,
    "SESSION_LOGIN": False,
}

# ── Simple JWT  (token lifetimes used by drf-auth-kit) ───────────────────
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# ── drf-spectacular  (OpenAPI / Swagger schema) ─────────────────────────
SPECTACULAR_SETTINGS = {
    "TITLE": "Mini Shop API",
    "VERSION": "0.1.0",
}

# ── django-payments  (dummy payment provider) ───────────────────────────
PAYMENT_HOST = "localhost:8000"
PAYMENT_USES_SSL = False
PAYMENT_MODEL = "core.Payment"
PAYMENT_VARIANTS = {
    "default": ("payments.dummy.DummyProvider", {}),
}

# ── django-fernet-encrypted-fields ──────────────────────────────────────
SALT_KEY = "mini-shop-salt-key-for-demo"

# ── django-eav2 ─────────────────────────────────────────────────────────
EAV2_PRIMARY_KEY_FIELD = "django.db.models.BigAutoField"

# ── django-extensions  (graph_models settings) ──────────────────────────
GRAPH_MODELS = {
    "all_applications": True,
    "group_models": True,
}
